apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  # Sử dụng host.docker.internal để Backend (trong K8s) gọi ra Milvus (đang chạy bằng Docker Compose bên ngoài)
  MILVUS_URI: "http://host.docker.internal:19530"

